package soc.core.pipeline

import chisel3._
import chisel3.util._

import soc.config.Config
import soc.isa.MCause
import soc.isa.PrivilegeLevel

class MemoryAccessStage(XLEN: Int = 64) extends Module {
    val io = IO(new Bundle {
        val in    = Input(new MemoryAccessInfo(XLEN))
        val cfg   = Input(new MemorySystemConfig(XLEN))
        val out   = Output(new MemoryAccessInfo(XLEN))
        val fault = Output(new MemoryFaultInfo(XLEN))
    })

    private def inRegion(region: soc.config.AddressRegion): Bool = region.contains(io.in.vaddr, XLEN)

    val inRom    = inRegion(Config.RomRegion)
    val inSram   = inRegion(Config.SramRegion)
    val inDevice = Config.deviceRegions.map(inRegion).reduce(_ || _)

    val translateEnabled = io.in.valid && io.cfg.mmu_en && (io.cfg.satp =/= 0.U) && !io.in.attrs.device
    val isLoad = io.in.op === MemOpType.Load || io.in.op === MemOpType.LR
    val isStore = io.in.op === MemOpType.Store || io.in.op === MemOpType.SC || io.in.op === MemOpType.AMO

    val accessBytes = 1.U(XLEN.W) << io.in.size
    val accessStart = io.in.vaddr
    val accessEnd = io.in.vaddr + accessBytes - 1.U

    private def pmpCfg(index: Int): UInt = io.cfg.pmpcfg0(8 * index + 7, 8 * index)
    private def pmpAddrBytes(index: Int): UInt = (io.cfg.pmpaddr(index) << 2)(XLEN - 1, 0)

    val pmpMatches = Wire(Vec(8, Bool()))
    val pmpPermOk = Wire(Vec(8, Bool()))
    val pmpLocked = Wire(Vec(8, Bool()))

    for (i <- 0 until 8) {
        val cfg = pmpCfg(i)
        val mode = cfg(4, 3)
        val read = cfg(0)
        val write = cfg(1)
        val lower = if (i == 0) 0.U(XLEN.W) else pmpAddrBytes(i - 1)
        val upper = pmpAddrBytes(i)
        val torMatch = accessStart >= lower && accessEnd < upper
        val na4Match = accessStart >= upper && accessEnd < upper + 4.U

        // NAPOT encodes the naturally aligned region size in the low set bits
        // of pmpaddr. The generated byte mask covers the complete region.
        val napotMask = (((io.cfg.pmpaddr(i) ^ (io.cfg.pmpaddr(i) + 1.U)) << 2) | 3.U)(XLEN - 1, 0)
        val napotBase = upper & ~napotMask
        val napotMatch = (accessStart & ~napotMask) === napotBase &&
            (accessEnd & ~napotMask) === napotBase

        pmpMatches(i) := MuxLookup(mode, false.B)(
            Seq(
                1.U -> torMatch,
                2.U -> na4Match,
                3.U -> napotMatch
            )
        )
        pmpPermOk(i) := Mux(isStore, write, read)
        pmpLocked(i) := cfg(7)
    }

    val matchedEntry = PriorityEncoder(pmpMatches)
    val pmpAnyMatch = pmpMatches.asUInt.orR
    val matchedPermOk = pmpPermOk(matchedEntry)
    val matchedLocked = pmpLocked(matchedEntry)
    val pmpFault = io.in.valid && (isLoad || isStore) && Mux(
        io.cfg.priv === PrivilegeLevel.Machine,
        pmpAnyMatch && matchedLocked && !matchedPermOk,
        !pmpAnyMatch || !matchedPermOk
    )

    io.out := io.in
    io.out.paddr := io.in.vaddr
    io.out.attrs.cacheable  := inSram
    io.out.attrs.device     := inDevice
    io.out.attrs.bufferable := inSram
    io.out.attrs.allocate   := inSram
    io.out.attrs.translate  := translateEnabled
    io.out.attrs.executable := inRom

    io.fault.valid := pmpFault
    io.fault.cause := Mux(isStore, MCause.StoreAccessFault, MCause.LoadAccessFault)
    io.fault.value := io.in.vaddr
}
